# -*- coding: utf-8 -*-

"""
wordsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.authentication.header_auth import HeaderAuth


class CustomHeaderAuthentication(HeaderAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in CustomHeaderAuthentication

        """
        return "CustomHeaderAuthentication: X-RapidAPI-Key is undefined."

    def __init__(self, x_rapid_api_key):
        auth_params = {}
        if x_rapid_api_key:
            auth_params["X-RapidAPI-Key"] = x_rapid_api_key
        super().__init__(auth_params=auth_params)
        self._x_rapid_api_key = x_rapid_api_key
